[rcon]
host = '127.0.0.1:12345'
password = 'password'
mode = 'factorio'

[twitch]
# To get an auth token, visit the following URL:
# https://id.twitch.tv/oauth2/authorize?client_id=lm0k1rk7zowacwnrfmk8c7gxteft9r&redirect_uri=https://barinzaya.github.io/oauth.html&response_type=token&scope=channel:read:redemptions
#
# Paste the token inside of the quotes below
auth-token = ''

[[redeems]]
reward = 'Attack (Factorio)'
command = '/Attack'

limit = 12
name = 'Barinzaya'

[[redeems]]
reward = 'Paranoia (Factorio)'
command = '/Paranoia'

limit = 15
radius = 200
name = 'Barinzaya'

[[redeems]]
reward = 'Stinky (Factorio)'
command = '/SpawnPollution'

pollution = 240
name = 'Barinzaya'

[[redeems]]
reward = 'Teleport (Factorio)'
command = '/Teleport'

radius = 100
name = 'Barinzaya'
